

server:
  port: 8080
#  ssl:
#        enabled: true
#        key-store: certificate.pfx
#        key-store-type: PKCS12
#        key-store-password: 123456
#  ssl:
#        enabled: true
#        key-store: aaa.p12
#        key-store-type: PKCS12
#        key-store-password: 123456  
  tomcat:
   additional-tld-skip-patterns: "*.jar"
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    session:
      timeout: 14400
  
      
mybatis:
    mapper-locations: 'mybatis/**/*.xml '
    type-aliases-package: com.mvc.forrest.service.domain
 
    
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  messages:
    basename: messages,errors
    
    
  thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      mode: HTML
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/forrest?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
 

    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:  14488329bb0ccdf08f6b761a0726ab5a
            client-secret: hFK6mQZSrHsK9N4Z8otthg1qg44VmzLf
            client-name: Kakao
#            redirect-uri: https://for-rest.kro.kr/login/oauth2/code/kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: 
              - account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          
          naver:
            client-id:  RxuYhXapOnqUmHtxXu7S
            client-secret: XGYQZxDwdG
            client-name: Naver
#            redirect-uri: http://192.168.0.8:8080/login/oauth2/code/naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: email, profile_image
            authorization-grant-type: authorization_code
            client-authentication-method: POST
       
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token 
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute : response            

file:
  path: C:/imgs/

            
fcm:
  certification: bit-project-runrunfunfun-firebase-adminsdk-6odpy-69715e90cd.json
  
iamportApi:
  api_key: 8740787114435303
  api_secret: 7f0c791b9cc0f3739e67cf5e3116f1d769ae64b9372cd0d16248fa803279c5cdbf74600ab0166d1b
